### PR TITLE
Bluetooth printing

### PR DESCRIPTION
**Pull request by muhammad-ajmal-arkhitech**
## Changelog

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Comment by tux2nicolae** [comment]
I'm interested in this PR to be merged as well

**Comment by muhammad-ajmal-arkhitech** [comment]
> I'm interested in this PR to be merged as well

Thanks @tux2nicolae.
@HeligPfleigh Kindly merge this. It will be helpful to others as well.

**Comment by muhammad-ajmal-arkhitech** [comment]
Great, thanks!

**Comment by muhammad-ajmal-arkhitech** [comment]
Please merge this HeligPfleigh/react-native-thermal-receipt-printer

**Comment by tux2nicolae** [comment]
@muhammad-ajmal-arkhitech it's already merged :)

**Pull request merged**
